# FROM docker.io/library/python:3.11
# LABEL maintainer="Kennethwu"

# WORKDIR /app/
# COPY requirements.txt /app/requirements.txt
# RUN pip install -r requirements.txt

# COPY app.py /app/app.py
# COPY pages /app/pages
# COPY images /app/images
# COPY .streamlit /app/.streamlit
# ENTRYPOINT ["streamlit run app.py", "-b"]
FROM alpine:3.19.1
# FROM python:3.11-slim
LABEL maintainer="Kennethwu"

RUN apk update && apk add --no-cache \
    py3-pip \
    py3-pyarrow

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt
# RUN pip3 install --no-cache-dir -r requirements.txt
COPY app.py /app/app.py
COPY pages /app/pages
COPY images /app/images
COPY .streamlit /app/.streamlit
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
# ENTRYPOINT ["streamlit", "run", "app.py"]