services:
    web-app:
        image: sebalaxi/office-translator-web-app:latest
        container_name: "web-app"
        ports:
            - "8080:8501"
        environment:
            - CONTROLLER_ENDPOINT=http://controller:8080
        entrypoint: ["python", "-m", "streamlit", "run", "app.py"]
    controller:
        image: sebalaxi/office-translator:latest
        ports:
            - "8081:8080"
        volumes:
            - "${PWD}/data/file_repo:/app/file_repo"
        environment:
            - DB_HOST=mysql
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=office_translator
            - KAFKA_TOPIC_PPTX=pptx-translate
            - KAFKA_TOPIC_STATUS_UPDATE=status-update
            - KAFKA_SERVERS=broker:9092
            - TZ=Asia/Shanghai
        container_name: "controller"
        entrypoint: ["python", "httpd.py"]
        depends_on:
          - mysql
          - broker
    worker:
        image: sebalaxi/office-translator:latest
        container_name: "worker"
        entrypoint: ["python", "pptx_translator.py"]
        restart: unless-stopped
        depends_on:
          - broker
        environment:
            - KAFKA_SERVERS=broker:9092
            - KAFKA_TOPIC_PPTX=pptx-translate
            - KAFKA_TOPIC_STATUS_UPDATE=status-update
            - OLLAMA_URL=http://ollama:11434  # or use api endpoint of ollama outside
            - TZ=Asia/Shanghai
    mysql:
        image: mysql:9.1.0
        expose:
            - 3306
            # - 33060
        volumes:
            - "${PWD}/data/mysql:/var/lib/mysql"
        # 环境变量
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=office_translator
        container_name: "mysql"

    broker:
        image: apache/kafka:3.8.1
        container_name: broker
        expose:
            - 9092
            - 9093
        environment:
            - KAFKA_NODE_ID=1
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_NUM_PARTITIONS=1
    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        expose:
            - 11434
        ports:
            - 11434:11434
        environment:
            - OLLAMA_HOST=0.0.0.0:11434
        volumes:
            - "${PWD}/data/ollama:/root/.ollama"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
