FROM docker.io/library/python:3.11-alpine

LABEL maintainer="Kennethwu"

# RUN apt update && apt -y install inetutils-ping netcat-openbsd net-tools
# RUN apk update && apk add netcat-openbsd 

WORKDIR /app/
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY httpd.py /app/httpd.py
COPY task.py /app/task.py
COPY pptx_translator.py /app/pptx_translator.py
COPY dont-translate-word.txt /app/dont-translate-word.txt
ENTRYPOINT ["python /app/httpd.py", "-b"]
