services:
    web-app:
        image: sebalaxi/office-translator-web-app:latest
        container_name: "web-app"
        ports:
            - "8080:8501"
        volumes:
            - "${PWD}/data/file_repo:/app/file_repo"
        environment:
            - CONTROLLER_ENDPOINT=http://controller
            - TZ=Asia/Shanghai
        entrypoint: ["python", "-m", "streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.maxUploadSize", "250"]
    controller:
        image: sebalaxi/office-translator:latest
        ports:
            # - "8081:80"
            - "80"
        volumes:
            - "${PWD}/data/file_repo:/app/file_repo"
        restart: unless-stopped
        environment:
            - DB_HOST=mysql
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=office_translator
            - KAFKA_TOPIC_PPTX=pptx-translate
            - KAFKA_TOPIC_STATUS_UPDATE=status-update
            - KAFKA_SERVERS=broker:9092
            - TZ=Asia/Shanghai
        # container_name: "controller"
        scale: 1
        entrypoint: ["uvicorn", "httpd:app", "--host", "0.0.0.0", "--port", "80"]
        depends_on:
          - mysql
          - broker
    worker:
        image: sebalaxi/office-translator:latest
        entrypoint: ["python", "pptx_translator.py"]
        restart: unless-stopped
        volumes:
            - "${PWD}/data/file_repo:/app/file_repo"
        depends_on:
          - broker
        environment:
            - KAFKA_SERVERS=broker:9092
            - KAFKA_TOPIC_PPTX=pptx-translate
            - KAFKA_TOPIC_STATUS_UPDATE=status-update
            - OLLAMA_URL=http://${host_ip}:11434  # only for mac
            - TZ=Asia/Shanghai
    mysql:
        image: mysql:9.1.0
        ports:
            - "3306:3306"
            # - 33060
        volumes:
            - "${PWD}/data/mysql:/var/lib/mysql"
        # 环境变量
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=office_translator
            - TZ=Asia/Shanghai

    broker:
        image: apache/kafka:3.8.1
        container_name: broker
        expose:
            - 9092
            - 9093
        environment:
            - KAFKA_NODE_ID=1
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_NUM_PARTITIONS=1
            - TZ=Asia/Shanghai
